### ISSUE TITLE
run evaluations on test set with feature combination subsets 

### ISSUE THREAD

**Issue by EdoardoPona** [EdoardoPona/predicting-inductive-biases-RL#10]
We want to evaluate performance on the test set for the subsets `weak, strong, neither, both` as in the Lovering et. al work.

**Comment by EdoardoPona** [comment]
implemented in 23f391915399961be4a4424c021475704fd16969.
The commit https://github.com/allenai/RL4LMs/commit/1bb581f0f018683a599c22d575624b20558b4826 adds the rl4lms data pool functionality of evaluating on arbitrary custom splits. 
These have to be passed to in the config as such: 
```
datapool:
  id: toy_pool
  custom_splits: ['strong', 'weak', 'both', 'neither']
  args:
    toy: {toy}
    rate: {rate}
```

The split datasets have to be pre-generated, similarly to what is done in subset_split.py
